-- 24.04.01 추가
/*
	페이징 방법
	10g - ROWNUM
	11g - ROWNUMBER
	12g - OFFSET FETCH
*/

--DELETE FROM BOARD WHERE BNO IN (998, 996, 902, 899, 898);
--COMMIT;

-- 테이블에 샘플 데이터를 추가(1000개)
DECLARE
    DATA1 VARCHAR2(100) := 'JAVA 게시물 ';
BEGIN
    FOR I IN  23 .. 1000
    LOOP
        INSERT INTO BOARD (BNO, MENU_ID, TITLE, CONTENT, WRITER, REGDATE, HIT) VALUES (I, 'MENU01', DATA1 || I, '내용', 'USER01', SYSDATE, 0);
    END LOOP;
    COMMIT;
END;

--1) ROWNUM 사용
--SELECT ROWNUM, BNO, MENU_ID, TITLE, CONTENT, WRITER, REGDATE, HIT FROM BOARD ORDER BY BNO DESC;

--2) ROW_NUMBER 사용 -> ROWNUM 대신 사용, ROWNUM은 정렬하거나 하면 숫자 매기는 순서가 이상해짐
SELECT *
FROM 
    (SELECT ROW_NUMBER() OVER (ORDER BY BNO DESC) RN, BNO, MENU_ID, TITLE, CONTENT, WRITER, REGDATE, HIT FROM BOARD) T
WHERE T.RN BETWEEN 11 AND 20;

--수행 시간 확인
SET TIMING ON 
SELECT *
FROM 
    (SELECT ROW_NUMBER() OVER (ORDER BY BNO DESC) RN, BNO, MENU_ID, TITLE, CONTENT, WRITER, REGDATE, HIT FROM BOARD) T
WHERE T.RN BETWEEN 11 AND 20;

--3) OFFSET FETCH
SELECT BNO, MENU_ID, TITLE, CONTENT, WRITER, TO_CHAR(REGDATE, 'YYYY-MM-DD'), HIT FROM BOARD ORDER BY BNO DESC
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;